apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:                # This is the label of the replicaset. This is used to identify the replicaset only.
    app: nginx             
    tier: frontend
    project: expense
spec:
  replicas: 3               # Number of pods to be created
  selector:
    matchLabels:         # This should be the label of the pod to which this replicaset will manage          
      app: nginx             
      tier: frontend
      project: expense
  template:
    metadata:
      labels:             # (This is the label of the pod) this label should be same as matchLabels of selector  
        app: nginx             
        tier: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: rohanraghu/frontend:v1
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
spec:
  type: LoadBalancer
  selector:           # This is the label of the pod to which this service will route the traffic
    app: nginx             
    tier: frontend
    project: expense    
  ports:
  - name: nginx-service
    port: 80         # Service Port , this is for other containers to communicate with nginx container
    targetPort: 80   # Container Port
    protocol: TCP
